service: hacker-toolkit
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  get_osint:
    handler: toolkit.get_osint
    events:
      - http:
          path: osint/{domain}
          method: get
plugins:
  - serverless-python-requirements
